export default {
  name: 'servicesBlock',
  type: 'object',
  title: 'Services block',
  fieldsets: [
    { name: 'first', title: 'Fields for first card' },
    { name: 'second', title: 'Fields for second card' },
    { name: 'third', title: 'Fields for third card' },
  ],
  fields: [
    {
      name: 'preTitle',
      type: 'string',
      title: 'Small text before title',
      description: '(required field)',
      validation: (Rule) => Rule.error('The field is required').required(),
    },
    {
      name: 'title',
      type: 'string',
      title: 'Section title',
      description: '(required field)',
      validation: (Rule) => Rule.error('The section title is required').required(),
    },
    {
      name: 'firstTitle',
      type: 'string',
      fieldset: 'first',
      title: 'Title for first card',
      description: '(required field)',
      validation: (Rule) => Rule.error('The card title is required').required(),
    },
    {
      name: 'firstDescription',
      type: 'text',
      fieldset: 'first',
      title: 'Description for first card',
      description: '(required field)',
      validation: (Rule) => Rule.error('The card description is required').required(),
    },
    {
      name: 'secondTitle',
      type: 'string',
      fieldset: 'second',
      title: 'Title for second card',
      description: '(required field)',
      validation: (Rule) => Rule.error('The card title is required').required(),
    },
    {
      name: 'secondDescription',
      type: 'text',
      fieldset: 'second',
      title: 'Description for second card',
      description: '(required field)',
      validation: (Rule) => Rule.error('The card description is required').required(),
    },
    {
      name: 'thirdTitle',
      type: 'string',
      fieldset: 'third',
      title: 'Title for third card',
      description: '(required field)',
      validation: (Rule) => Rule.error('The card title is required').required(),
    },
    {
      name: 'thirdDescription',
      type: 'text',
      fieldset: 'third',
      title: 'Description for third card',
      description: '(required field)',
      validation: (Rule) => Rule.error('The card description is required').required(),
    },
  ],
}
